version: '3.1'

services:
  gateway:
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.tcp_timestamps=1
    restart: on-failure:10
    container_name: gateway-api
    depends_on:
      - card
      - card-payment
    build:
      context: ./gateway-go
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CARD_HOST=card:5000
      - CARD_PAYMENT_HOST=card-payment:5000
      - GRPC_ENABLED
      - GOMAXPROCS=8
    networks:
      - base

  card:
    restart: on-failure:10
    container_name: card-api
    depends_on:
      - card-db
    build:
      context: ./card
      dockerfile: Dockerfile.prod
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - DATABASE_HOST=card-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=card-ms
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - GRPC_ENABLED
      - GOMAXPROCS=8
    networks:
      - base

  card-payment:
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.tcp_timestamps=1
    restart: on-failure:10
    container_name: card-payment-api
    depends_on:
      - card-payment-db
    build:
      context: ./card-payment
      dockerfile: Dockerfile.prod
    ports:
      - "5002:5000"
    environment:
      - PORT=5000
      - CARD_HOST=card:5000
      - DATABASE_HOST=card-payment-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=card-payment-ms
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - GRPC_ENABLED
      - GOMAXPROCS=8
    networks:
      - base

  card-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: card-ms
    ports:
      - "5432:5432"
    volumes:
      - card_db_data:/var/lib/postgresql/data
      - ./card/src/migrations/01-create-cards-table.sql:/docker-entrypoint-initdb.d/01-create-cards-table.sql
    networks:
      - base

  card-payment-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: card-payment-ms
    ports:
      - "5433:5432"
    volumes:
      - card_payment_db_data:/var/lib/postgresql/data
      - ./card-payment/src/migrations/01-create-tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql
    networks:
      - base

networks:
  base:


volumes:
  card_db_data:
  card_payment_db_data:
