// source: client_wallet.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.clientwallet.CreateTransactionInput', null, global);
goog.exportSymbol('proto.clientwallet.ServiceTypeEnum', null, global);
goog.exportSymbol('proto.clientwallet.Transaction', null, global);
goog.exportSymbol('proto.clientwallet.TransactionTypeEnum', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.clientwallet.Transaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.clientwallet.Transaction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.clientwallet.Transaction.displayName = 'proto.clientwallet.Transaction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.clientwallet.CreateTransactionInput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.clientwallet.CreateTransactionInput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.clientwallet.CreateTransactionInput.displayName = 'proto.clientwallet.CreateTransactionInput';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.clientwallet.Transaction.prototype.toObject = function(opt_includeInstance) {
  return proto.clientwallet.Transaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.clientwallet.Transaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.clientwallet.Transaction.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    clientId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    transactionServiceId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    service: jspb.Message.getFieldWithDefault(msg, 6, 0),
    transactionDate: jspb.Message.getFieldWithDefault(msg, 7, ""),
    createdAt: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.clientwallet.Transaction}
 */
proto.clientwallet.Transaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.clientwallet.Transaction;
  return proto.clientwallet.Transaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.clientwallet.Transaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.clientwallet.Transaction}
 */
proto.clientwallet.Transaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 4:
      var value = /** @type {!proto.clientwallet.TransactionTypeEnum} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionServiceId(value);
      break;
    case 6:
      var value = /** @type {!proto.clientwallet.ServiceTypeEnum} */ (reader.readEnum());
      msg.setService(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionDate(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.clientwallet.Transaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.clientwallet.Transaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.clientwallet.Transaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.clientwallet.Transaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getClientId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTransactionServiceId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getService();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getTransactionDate();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.clientwallet.Transaction.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.clientwallet.Transaction} returns this
 */
proto.clientwallet.Transaction.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string client_id = 2;
 * @return {string}
 */
proto.clientwallet.Transaction.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.clientwallet.Transaction} returns this
 */
proto.clientwallet.Transaction.prototype.setClientId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double amount = 3;
 * @return {number}
 */
proto.clientwallet.Transaction.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.clientwallet.Transaction} returns this
 */
proto.clientwallet.Transaction.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional TransactionTypeEnum type = 4;
 * @return {!proto.clientwallet.TransactionTypeEnum}
 */
proto.clientwallet.Transaction.prototype.getType = function() {
  return /** @type {!proto.clientwallet.TransactionTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.clientwallet.TransactionTypeEnum} value
 * @return {!proto.clientwallet.Transaction} returns this
 */
proto.clientwallet.Transaction.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string transaction_service_id = 5;
 * @return {string}
 */
proto.clientwallet.Transaction.prototype.getTransactionServiceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.clientwallet.Transaction} returns this
 */
proto.clientwallet.Transaction.prototype.setTransactionServiceId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional ServiceTypeEnum service = 6;
 * @return {!proto.clientwallet.ServiceTypeEnum}
 */
proto.clientwallet.Transaction.prototype.getService = function() {
  return /** @type {!proto.clientwallet.ServiceTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.clientwallet.ServiceTypeEnum} value
 * @return {!proto.clientwallet.Transaction} returns this
 */
proto.clientwallet.Transaction.prototype.setService = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional string transaction_date = 7;
 * @return {string}
 */
proto.clientwallet.Transaction.prototype.getTransactionDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.clientwallet.Transaction} returns this
 */
proto.clientwallet.Transaction.prototype.setTransactionDate = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string created_at = 8;
 * @return {string}
 */
proto.clientwallet.Transaction.prototype.getCreatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.clientwallet.Transaction} returns this
 */
proto.clientwallet.Transaction.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.clientwallet.CreateTransactionInput.prototype.toObject = function(opt_includeInstance) {
  return proto.clientwallet.CreateTransactionInput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.clientwallet.CreateTransactionInput} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.clientwallet.CreateTransactionInput.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0),
    service: jspb.Message.getFieldWithDefault(msg, 4, 0),
    transactionServiceId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    transactionDate: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.clientwallet.CreateTransactionInput}
 */
proto.clientwallet.CreateTransactionInput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.clientwallet.CreateTransactionInput;
  return proto.clientwallet.CreateTransactionInput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.clientwallet.CreateTransactionInput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.clientwallet.CreateTransactionInput}
 */
proto.clientwallet.CreateTransactionInput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 3:
      var value = /** @type {!proto.clientwallet.TransactionTypeEnum} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {!proto.clientwallet.ServiceTypeEnum} */ (reader.readEnum());
      msg.setService(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionServiceId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.clientwallet.CreateTransactionInput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.clientwallet.CreateTransactionInput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.clientwallet.CreateTransactionInput} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.clientwallet.CreateTransactionInput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getService();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTransactionServiceId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTransactionDate();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string client_id = 1;
 * @return {string}
 */
proto.clientwallet.CreateTransactionInput.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.clientwallet.CreateTransactionInput} returns this
 */
proto.clientwallet.CreateTransactionInput.prototype.setClientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double amount = 2;
 * @return {number}
 */
proto.clientwallet.CreateTransactionInput.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.clientwallet.CreateTransactionInput} returns this
 */
proto.clientwallet.CreateTransactionInput.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional TransactionTypeEnum type = 3;
 * @return {!proto.clientwallet.TransactionTypeEnum}
 */
proto.clientwallet.CreateTransactionInput.prototype.getType = function() {
  return /** @type {!proto.clientwallet.TransactionTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.clientwallet.TransactionTypeEnum} value
 * @return {!proto.clientwallet.CreateTransactionInput} returns this
 */
proto.clientwallet.CreateTransactionInput.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional ServiceTypeEnum service = 4;
 * @return {!proto.clientwallet.ServiceTypeEnum}
 */
proto.clientwallet.CreateTransactionInput.prototype.getService = function() {
  return /** @type {!proto.clientwallet.ServiceTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.clientwallet.ServiceTypeEnum} value
 * @return {!proto.clientwallet.CreateTransactionInput} returns this
 */
proto.clientwallet.CreateTransactionInput.prototype.setService = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string transaction_service_id = 5;
 * @return {string}
 */
proto.clientwallet.CreateTransactionInput.prototype.getTransactionServiceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.clientwallet.CreateTransactionInput} returns this
 */
proto.clientwallet.CreateTransactionInput.prototype.setTransactionServiceId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string transaction_date = 6;
 * @return {string}
 */
proto.clientwallet.CreateTransactionInput.prototype.getTransactionDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.clientwallet.CreateTransactionInput} returns this
 */
proto.clientwallet.CreateTransactionInput.prototype.setTransactionDate = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * @enum {number}
 */
proto.clientwallet.TransactionTypeEnum = {
  CREDIT_CARD_PAYMENT: 0,
  DEBIT_CARD_PAYMENT: 1,
  WITHDRAWAL: 2
};

/**
 * @enum {number}
 */
proto.clientwallet.ServiceTypeEnum = {
  CARD_PAYMENT: 0,
  INTERNAL: 1
};

goog.object.extend(exports, proto.clientwallet);
