version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: "cards-payments"
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/migrations/01-create-tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql

volumes:
  db_data: