@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@contentType = application/json

###

# Generate Card
POST {{host}}/api/cards
Content-Type: application/json

{
    "cardholder_name": "John Doe",
    "is_credit": true,
    "is_debit": true
}

###

@token = 0TsxAesmDiCKkTtAlxokM4SWk1hv035otGpa/zB1DwQ=

# Find card by token
GET {{host}}/api/cards?token={{token}}
Content-Type: application/json