// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: card-payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentTypeEnum int32

const (
	PaymentTypeEnum_CREDIT_CARD PaymentTypeEnum = 0
	PaymentTypeEnum_DEBIT_CARD  PaymentTypeEnum = 1
)

// Enum value maps for PaymentTypeEnum.
var (
	PaymentTypeEnum_name = map[int32]string{
		0: "CREDIT_CARD",
		1: "DEBIT_CARD",
	}
	PaymentTypeEnum_value = map[string]int32{
		"CREDIT_CARD": 0,
		"DEBIT_CARD":  1,
	}
)

func (x PaymentTypeEnum) Enum() *PaymentTypeEnum {
	p := new(PaymentTypeEnum)
	*p = x
	return p
}

func (x PaymentTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_card_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentTypeEnum) Type() protoreflect.EnumType {
	return &file_card_payment_proto_enumTypes[0]
}

func (x PaymentTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentTypeEnum.Descriptor instead.
func (PaymentTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_card_payment_proto_rawDescGZIP(), []int{0}
}

type ProcessCardPaymentInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId    string            `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	PaymentType PaymentTypeEnum   `protobuf:"varint,2,opt,name=paymentType,proto3,enum=cardpayment.PaymentTypeEnum" json:"paymentType,omitempty"`
	PaymentDate string            `protobuf:"bytes,3,opt,name=paymentDate,proto3" json:"paymentDate,omitempty"`
	Amount      float32           `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentInfo *PaymentInfoInput `protobuf:"bytes,5,opt,name=paymentInfo,proto3" json:"paymentInfo,omitempty"`
}

func (x *ProcessCardPaymentInput) Reset() {
	*x = ProcessCardPaymentInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_payment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessCardPaymentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCardPaymentInput) ProtoMessage() {}

func (x *ProcessCardPaymentInput) ProtoReflect() protoreflect.Message {
	mi := &file_card_payment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCardPaymentInput.ProtoReflect.Descriptor instead.
func (*ProcessCardPaymentInput) Descriptor() ([]byte, []int) {
	return file_card_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessCardPaymentInput) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProcessCardPaymentInput) GetPaymentType() PaymentTypeEnum {
	if x != nil {
		return x.PaymentType
	}
	return PaymentTypeEnum_CREDIT_CARD
}

func (x *ProcessCardPaymentInput) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

func (x *ProcessCardPaymentInput) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessCardPaymentInput) GetPaymentInfo() *PaymentInfoInput {
	if x != nil {
		return x.PaymentInfo
	}
	return nil
}

type PaymentInfoInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardToken string `protobuf:"bytes,1,opt,name=cardToken,proto3" json:"cardToken,omitempty"`
}

func (x *PaymentInfoInput) Reset() {
	*x = PaymentInfoInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_payment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentInfoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfoInput) ProtoMessage() {}

func (x *PaymentInfoInput) ProtoReflect() protoreflect.Message {
	mi := &file_card_payment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfoInput.ProtoReflect.Descriptor instead.
func (*PaymentInfoInput) Descriptor() ([]byte, []int) {
	return file_card_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentInfoInput) GetCardToken() string {
	if x != nil {
		return x.CardToken
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId    string       `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	PaymentType string       `protobuf:"bytes,3,opt,name=paymentType,proto3" json:"paymentType,omitempty"`
	PaymentDate string       `protobuf:"bytes,4,opt,name=paymentDate,proto3" json:"paymentDate,omitempty"`
	Amount      float32      `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentInfo *PaymentInfo `protobuf:"bytes,6,opt,name=paymentInfo,proto3" json:"paymentInfo,omitempty"`
}

func (x *Payment) Reset() {
	*x = Payment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_payment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_card_payment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_card_payment_proto_rawDescGZIP(), []int{2}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Payment) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *Payment) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

func (x *Payment) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetPaymentInfo() *PaymentInfo {
	if x != nil {
		return x.PaymentInfo
	}
	return nil
}

type PaymentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaskedNumber string `protobuf:"bytes,1,opt,name=maskedNumber,proto3" json:"maskedNumber,omitempty"`
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_payment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_card_payment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_card_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentInfo) GetMaskedNumber() string {
	if x != nil {
		return x.MaskedNumber
	}
	return ""
}

var File_card_payment_proto protoreflect.FileDescriptor

var file_card_payment_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x72, 0x64, 0x2d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0xf0, 0x01, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x43, 0x61, 0x72,
	0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x0b, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x63, 0x61, 0x72, 0x64, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0b, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x30, 0x0a, 0x10, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x72,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xcd, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x31, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x73,
	0x6b, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2a, 0x32, 0x0a, 0x0f, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a,
	0x0a, 0x44, 0x45, 0x42, 0x49, 0x54, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10, 0x01, 0x32, 0x62, 0x0a,
	0x0b, 0x43, 0x61, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x53, 0x0a, 0x13,
	0x50, 0x72, 0x6f, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x61, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x43, 0x61, 0x72, 0x64, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x14, 0x2e, 0x63, 0x61, 0x72, 0x64,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x62, 0x6d, 0x76, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x75, 0x73, 0x73, 0x2f, 0x74, 0x63, 0x63, 0x2f,
	0x63, 0x61, 0x72, 0x64, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_card_payment_proto_rawDescOnce sync.Once
	file_card_payment_proto_rawDescData = file_card_payment_proto_rawDesc
)

func file_card_payment_proto_rawDescGZIP() []byte {
	file_card_payment_proto_rawDescOnce.Do(func() {
		file_card_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_card_payment_proto_rawDescData)
	})
	return file_card_payment_proto_rawDescData
}

var file_card_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_card_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_card_payment_proto_goTypes = []interface{}{
	(PaymentTypeEnum)(0),            // 0: cardpayment.PaymentTypeEnum
	(*ProcessCardPaymentInput)(nil), // 1: cardpayment.ProcessCardPaymentInput
	(*PaymentInfoInput)(nil),        // 2: cardpayment.PaymentInfoInput
	(*Payment)(nil),                 // 3: cardpayment.Payment
	(*PaymentInfo)(nil),             // 4: cardpayment.PaymentInfo
}
var file_card_payment_proto_depIdxs = []int32{
	0, // 0: cardpayment.ProcessCardPaymentInput.paymentType:type_name -> cardpayment.PaymentTypeEnum
	2, // 1: cardpayment.ProcessCardPaymentInput.paymentInfo:type_name -> cardpayment.PaymentInfoInput
	4, // 2: cardpayment.Payment.paymentInfo:type_name -> cardpayment.PaymentInfo
	1, // 3: cardpayment.CardPayment.ProccessCardPayment:input_type -> cardpayment.ProcessCardPaymentInput
	3, // 4: cardpayment.CardPayment.ProccessCardPayment:output_type -> cardpayment.Payment
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_card_payment_proto_init() }
func file_card_payment_proto_init() {
	if File_card_payment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_card_payment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessCardPaymentInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_payment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentInfoInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_payment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_card_payment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_card_payment_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_payment_proto_goTypes,
		DependencyIndexes: file_card_payment_proto_depIdxs,
		EnumInfos:         file_card_payment_proto_enumTypes,
		MessageInfos:      file_card_payment_proto_msgTypes,
	}.Build()
	File_card_payment_proto = out.File
	file_card_payment_proto_rawDesc = nil
	file_card_payment_proto_goTypes = nil
	file_card_payment_proto_depIdxs = nil
}
