FROM golang:1.18-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /server ./src/api/main.go

FROM golang:1.18-alpine

WORKDIR /

COPY --from=builder /server /server

EXPOSE 5000
CMD ["/server"]
